import { describe, expect, it } from "vitest"
import {
  getUserSitePatternError,
  normalizeUrlPattern,
  sitePatternForHost,
  urlMatchesPattern,
} from "../url-pattern"

/**
 * Every URL the golden table is evaluated against. A pattern's `matches` list
 * names the ones it hits; every other URL here must NOT match, which is what
 * makes the table a real assertion rather than a list of happy paths.
 */
const URLS = [
  "https://x.com",
  "http://example.com",
  "https://x.com/path/to/page",
  "https://example.com?query=value",
  "https://x.com#section",
  "http://localhost:3000",
  "http://localhost",
  "https://Example.COM",
  "https://www.x.com",
  "https://api.dev.example.com",
  "https://blog.example.com/article",
  "https://API.Example.COM",
  "https://a.b.example.com/",
  "https://notx.com",
  "https://ax.com",
  "https://mygithub.com",
  "https://example.com.evil.com/",
  "https://user:pass@example.com",
  "http://192.168.1.1",
  "http://[::1]",
  "https://my-domain.com",
  "https://example123.com",
  "https://example.technology",
  "https://example.co.uk",
  "https://github.com/user/repo",
  "https://gist.github.com/user/123",
  "https://en.wikipedia.org/wiki/Article",
  "https://xn--r8jz45g.jp/",
  "https://example.com./",
  "http://example.com:8080/",
  "",
  "not-a-url",
  "/path/to/page",
  "example.com",
  "https://example .com",
  "undefined",
  "null",
  "chrome-extension://abcdefg/options.html",
  "file:///tmp/a.html",
  "about:blank",
] as const

/**
 * Frozen behaviour of the hostname-only matcher this module replaced
 * (`utils/url.ts`'s `matchDomainPattern`, deleted).
 *
 * Six user-facing website lists ran on that matcher — auto-translate,
 * never-auto-translate, the site-control black/whitelist, the floating button
 * and selection toolbar opt-outs — plus iframe injection. Their stored patterns
 * were rewritten to `*.host` by the config migration, and this table is the
 * proof that the rewrite preserves what each of those patterns used to match.
 * `stored` is what the migration (and `sitePatternForHost`) produces;
 * `matches` is what the OLD matcher returned for the raw pattern.
 *
 * Generated by running both implementations over URLS x patterns: 800 pairs,
 * 3 divergences, all of them the old matcher's bug (see the empty-pattern case
 * at the bottom). Do not hand-edit a row to make a change pass — a diff here
 * means user-visible behaviour moved.
 */
const GOLDEN: Array<{ pattern: string; stored: string; matches: string[] }> = [
  {
    pattern: "x.com",
    stored: "*.x.com",
    matches: [
      "https://x.com",
      "https://x.com/path/to/page",
      "https://x.com#section",
      "https://www.x.com",
    ],
  },
  {
    pattern: "example.com",
    stored: "*.example.com",
    matches: [
      "http://example.com",
      "https://example.com?query=value",
      "https://Example.COM",
      "https://api.dev.example.com",
      "https://blog.example.com/article",
      "https://API.Example.COM",
      "https://a.b.example.com/",
      "https://user:pass@example.com",
      "http://example.com:8080/",
    ],
  },
  {
    pattern: "EXAMPLE.com",
    stored: "*.example.com",
    matches: [
      "http://example.com",
      "https://example.com?query=value",
      "https://Example.COM",
      "https://api.dev.example.com",
      "https://blog.example.com/article",
      "https://API.Example.COM",
      "https://a.b.example.com/",
      "https://user:pass@example.com",
      "http://example.com:8080/",
    ],
  },
  {
    pattern: "  example.com  ",
    stored: "*.example.com",
    matches: [
      "http://example.com",
      "https://example.com?query=value",
      "https://Example.COM",
      "https://api.dev.example.com",
      "https://blog.example.com/article",
      "https://API.Example.COM",
      "https://a.b.example.com/",
      "https://user:pass@example.com",
      "http://example.com:8080/",
    ],
  },
  { pattern: "example.com.", stored: "*.example.com.", matches: ["https://example.com./"] },
  { pattern: "www.x.com", stored: "*.www.x.com", matches: ["https://www.x.com"] },
  { pattern: "x.co", stored: "*.x.co", matches: [] },
  {
    pattern: "localhost",
    stored: "*.localhost",
    matches: ["http://localhost:3000", "http://localhost"],
  },
  { pattern: "192.168.1.1", stored: "*.192.168.1.1", matches: ["http://192.168.1.1"] },
  { pattern: "[::1]", stored: "[::1]", matches: ["http://[::1]"] },
  { pattern: "my-domain.com", stored: "*.my-domain.com", matches: ["https://my-domain.com"] },
  { pattern: "example123.com", stored: "*.example123.com", matches: ["https://example123.com"] },
  {
    pattern: "example.technology",
    stored: "*.example.technology",
    matches: ["https://example.technology"],
  },
  { pattern: "example.co.uk", stored: "*.example.co.uk", matches: ["https://example.co.uk"] },
  { pattern: "co.uk", stored: "*.co.uk", matches: ["https://example.co.uk"] },
  {
    pattern: "com",
    stored: "*.com",
    matches: [
      "https://x.com",
      "http://example.com",
      "https://x.com/path/to/page",
      "https://example.com?query=value",
      "https://x.com#section",
      "https://Example.COM",
      "https://www.x.com",
      "https://api.dev.example.com",
      "https://blog.example.com/article",
      "https://API.Example.COM",
      "https://a.b.example.com/",
      "https://notx.com",
      "https://ax.com",
      "https://mygithub.com",
      "https://example.com.evil.com/",
      "https://user:pass@example.com",
      "https://my-domain.com",
      "https://example123.com",
      "https://github.com/user/repo",
      "https://gist.github.com/user/123",
      "http://example.com:8080/",
    ],
  },
  {
    pattern: "github.com",
    stored: "*.github.com",
    matches: ["https://github.com/user/repo", "https://gist.github.com/user/123"],
  },
  {
    pattern: "wikipedia.org",
    stored: "*.wikipedia.org",
    matches: ["https://en.wikipedia.org/wiki/Article"],
  },
  { pattern: "xn--r8jz45g.jp", stored: "*.xn--r8jz45g.jp", matches: ["https://xn--r8jz45g.jp/"] },
  { pattern: "", stored: "", matches: [] },
]

describe("website-list patterns keep their old meaning", () => {
  it.each(GOLDEN)("$pattern", ({ pattern, stored, matches }) => {
    expect(sitePatternForHost(pattern)).toBe(stored)

    for (const url of URLS) {
      expect(
        urlMatchesPattern(url, stored),
        `pattern ${JSON.stringify(stored)} vs url ${JSON.stringify(url)}`,
      ).toBe(matches.includes(url))
    }
  })

  /**
   * The one deliberate break. The old matcher compared
   * `hostname.endsWith("." + pattern)`, which for an empty pattern degrades to
   * `endsWith(".")` — so an empty pattern matched `file://` and `about:blank`
   * (hostname "") and any trailing-dot host. Nothing can add an empty pattern
   * through the UI, so this only ever reached a hand-edited config backup.
   */
  it("no longer lets an empty pattern match anything", () => {
    for (const url of ["https://example.com./", "file:///tmp/a.html", "about:blank"]) {
      expect(urlMatchesPattern(url, "")).toBe(false)
    }
  })
})

describe("sitePatternForHost", () => {
  it("expands a host the extension picked so it covers subdomains", () => {
    expect(sitePatternForHost("example.com")).toBe("*.example.com")
    expect(sitePatternForHost("  Example.COM  ")).toBe("*.example.com")
  })

  it("leaves anything that is already a pattern alone", () => {
    expect(sitePatternForHost("*.example.com")).toBe("*.example.com")
    expect(sitePatternForHost("example.com/docs/*")).toBe("example.com/docs/*")
    expect(sitePatternForHost("https://example.com")).toBe("https://example.com")
    expect(sitePatternForHost("*")).toBe("*")
  })

  it("leaves a colon alone rather than producing *.localhost:5173", () => {
    expect(sitePatternForHost("localhost:5173")).toBe("localhost:5173")
    expect(sitePatternForHost("[::1]")).toBe("[::1]")
  })

  it("is idempotent, so re-running the migration changes nothing", () => {
    for (const input of ["example.com", "*.example.com", "example.com/docs", "[::1]", ""]) {
      const once = sitePatternForHost(input)
      expect(sitePatternForHost(once)).toBe(once)
    }
  })
})

describe("getUserSitePatternError", () => {
  it("accepts whole-label wildcards", () => {
    for (const input of ["example.com", "*.example.com", "example.*", "*", "example.com/docs/*"]) {
      expect(getUserSitePatternError(input)).toBeNull()
    }
  })

  it("rejects a wildcard glued to text, which would not stop at a label", () => {
    // The reason this rule exists: `*example.com` compiles to a host regex of
    // `[a-z0-9.-]*example\.com`, which matches notexample.com.
    expect(getUserSitePatternError("*example.com")).toBe("gluedWildcard")
    expect(getUserSitePatternError("javdb*.com")).toBe("gluedWildcard")
    expect(getUserSitePatternError("*.yna*")).toBe("gluedWildcard")
  })

  it("rejects what the matcher would silently drop", () => {
    expect(getUserSitePatternError("localhost:5173")).toBe("unsupported")
    expect(getUserSitePatternError("ws://example.com/*")).toBe("unsupported")
    expect(getUserSitePatternError("file:///tmp/*")).toBe("unsupported")
  })

  it("reports an empty input separately so the caller can stay quiet about it", () => {
    expect(getUserSitePatternError("   ")).toBe("empty")
  })

  it("allows an IPv6 literal", () => {
    expect(getUserSitePatternError("[::1]")).toBeNull()
  })
})

describe("normalizeUrlPattern", () => {
  it("expands bare hostnames", () => {
    expect(normalizeUrlPattern("github.com")).toBe("*://github.com/*")
  })

  it("expands subdomain wildcards", () => {
    expect(normalizeUrlPattern("*.example.com")).toBe("*://*.example.com/*")
  })

  it("keeps paths verbatim", () => {
    expect(normalizeUrlPattern("github.com/settings")).toBe("*://github.com/settings")
    expect(normalizeUrlPattern("developer.apple.com/documentation/*")).toBe(
      "*://developer.apple.com/documentation/*",
    )
  })

  it("appends /* when a scheme is given without a path", () => {
    expect(normalizeUrlPattern("https://example.com")).toBe("https://example.com/*")
  })

  it("passes full match patterns through", () => {
    expect(normalizeUrlPattern("*://x.com/*")).toBe("*://x.com/*")
    expect(normalizeUrlPattern("https://www.npmjs.com/package/*")).toBe(
      "https://www.npmjs.com/package/*",
    )
  })

  it("lowercases scheme and host but not the path", () => {
    expect(normalizeUrlPattern("HTTPS://Example.COM/Path")).toBe("https://example.com/Path")
  })

  it("trims whitespace", () => {
    expect(normalizeUrlPattern("  github.com  ")).toBe("*://github.com/*")
  })

  it("allows the all-hosts wildcard", () => {
    expect(normalizeUrlPattern("*")).toBe("*://*/*")
  })

  it("keeps TLD and mid-host wildcards", () => {
    expect(normalizeUrlPattern("www.amazon.*")).toBe("*://www.amazon.*/*")
    expect(normalizeUrlPattern("javdb*.com")).toBe("*://javdb*.com/*")
  })

  it("keeps an IPv6 literal, whose colons are the address and not a port", () => {
    expect(normalizeUrlPattern("[::1]")).toBe("*://[::1]/*")
  })

  it("rejects unsupported input", () => {
    expect(normalizeUrlPattern("")).toBeNull()
    expect(normalizeUrlPattern("   ")).toBeNull()
    expect(normalizeUrlPattern("example.com:8080")).toBeNull()
    expect(normalizeUrlPattern("file:///etc/hosts")).toBeNull()
    expect(normalizeUrlPattern("ftp://example.com")).toBeNull()
  })
})

describe("urlMatchesPattern", () => {
  it("matches the exact host for bare hostnames, excluding subdomains", () => {
    expect(urlMatchesPattern("https://github.com/foo", "github.com")).toBe(true)
    expect(urlMatchesPattern("http://github.com/", "github.com")).toBe(true)
    expect(urlMatchesPattern("https://gist.github.com/foo", "github.com")).toBe(false)
  })

  /**
   * The dot after a leading `*` is optional, and everything about how a stored
   * `*.host` behaves rests on it. MatchPattern compiles two host regexes — the
   * pattern as written, and the pattern with a leading `*.` removed, dot
   * included — so the apex matches. The in-repo wildcard engine mirrors that by
   * collapsing a leading `[a-z0-9.-]*\.` into `(?:[^.]+\.)*`, which also
   * allows zero labels.
   */
  it("matches apex and subdomains for *. patterns", () => {
    expect(urlMatchesPattern("https://example.com/", "*.example.com")).toBe(true)
    expect(urlMatchesPattern("https://sub.example.com/x", "*.example.com")).toBe(true)
    expect(urlMatchesPattern("https://deep.sub.example.com/x", "*.example.com")).toBe(true)
    expect(urlMatchesPattern("https://notexample.com/", "*.example.com")).toBe(false)
    expect(urlMatchesPattern("https://example.com.evil.com/", "*.example.com")).toBe(false)
  })

  it("gives an exact host with any scheme when written the long way", () => {
    expect(urlMatchesPattern("https://example.com/", "*://example.com/*")).toBe(true)
    expect(urlMatchesPattern("http://example.com/x", "*://example.com/*")).toBe(true)
    expect(urlMatchesPattern("https://www.example.com/", "*://example.com/*")).toBe(false)
  })

  it("supports mid-path wildcards", () => {
    expect(urlMatchesPattern("https://github.com/a/b/settings", "github.com/*/settings")).toBe(true)
    expect(urlMatchesPattern("https://github.com/a/b", "github.com/*/settings")).toBe(false)
  })

  it("treats a path without a wildcard as exact, and is case-sensitive there", () => {
    expect(urlMatchesPattern("https://example.com/docs", "example.com/docs")).toBe(true)
    expect(urlMatchesPattern("https://example.com/docs/x", "example.com/docs")).toBe(false)
    expect(urlMatchesPattern("https://example.com/docs/x", "example.com/docs/*")).toBe(true)
    expect(urlMatchesPattern("https://example.com/docs", "example.com/Docs")).toBe(false)
  })

  it("ignores query strings", () => {
    expect(urlMatchesPattern("https://github.com/foo?tab=readme", "github.com/foo")).toBe(true)
    expect(urlMatchesPattern("https://example.com/a?q=1#h", "example.com/a")).toBe(true)
  })

  it("matches any TLD for trailing .* wildcards", () => {
    expect(urlMatchesPattern("https://www.amazon.com/dp/1", "www.amazon.*")).toBe(true)
    expect(urlMatchesPattern("https://www.amazon.co.jp/dp/1", "www.amazon.*")).toBe(true)
    expect(urlMatchesPattern("https://www.amazonaws.com/", "www.amazon.*")).toBe(false)
    expect(
      urlMatchesPattern("https://scholar.google.co.uk/scholar?q=x", "scholar.google.*/*"),
    ).toBe(true)
  })

  it("matches apex and subdomains for patterns with both leading and trailing wildcards", () => {
    expect(urlMatchesPattern("https://weibo.com/u/1", "*.weibo.*")).toBe(true)
    expect(urlMatchesPattern("https://m.weibo.cn/detail/2", "*.weibo.*")).toBe(true)
    expect(urlMatchesPattern("https://notweibo.com/", "*.weibo.*")).toBe(false)
  })

  it("matches mid-host wildcards", () => {
    expect(urlMatchesPattern("https://javdb007.com/x", "javdb*.com")).toBe(true)
    expect(urlMatchesPattern("https://javdb.com/x", "javdb*.com")).toBe(true)
    expect(urlMatchesPattern("https://example.com/", "javdb*.com")).toBe(false)
  })

  it("restricts wildcard-host patterns to http(s) and ignores query strings", () => {
    expect(urlMatchesPattern("ftp://www.amazon.com/", "www.amazon.*")).toBe(false)
    expect(urlMatchesPattern("https://www.amazon.de/dp/1?ref=nav", "www.amazon.*/dp/*")).toBe(true)
  })

  it("matches localhost and loopback IPs regardless of port", () => {
    expect(urlMatchesPattern("http://localhost:8000/", "localhost")).toBe(true)
    expect(urlMatchesPattern("http://localhost/chat", "localhost")).toBe(true)
    expect(urlMatchesPattern("http://127.0.0.1:8000/chat", "127.0.0.1")).toBe(true)
    expect(urlMatchesPattern("http://localhost.evil.com/", "localhost")).toBe(false)
    expect(urlMatchesPattern("http://[::1]:8000/x", "[::1]")).toBe(true)
  })

  it("returns false for URLs it cannot handle instead of throwing", () => {
    expect(urlMatchesPattern("not a url", "github.com")).toBe(false)
    expect(urlMatchesPattern("not a url", "www.amazon.*")).toBe(false)
    expect(urlMatchesPattern("file:///etc/hosts", "github.com")).toBe(false)
    expect(urlMatchesPattern("about:blank", "github.com")).toBe(false)
    expect(urlMatchesPattern("chrome-extension://abc/options.html", "*")).toBe(false)
  })

  it("returns false for invalid patterns instead of throwing", () => {
    expect(urlMatchesPattern("https://github.com/", "example.com:8080")).toBe(false)
    expect(urlMatchesPattern("https://github.com/", "")).toBe(false)
  })
})
